application: rare-basis-686
version: 1

runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: appsql.application

libraries:
- name: MySQLdb
  version: "latest"

- name: jinja2
  version: "latest"
